# project configuration

[tool.black]
line_length = 100
include = '((sqs_queue_viewer)/.*\.py$|tests/.*\.py$)'
#extend_exclude = '()'

[tool.isort]
profile = 'black'
#extend_skip = []
line_length = 100
